### ISSUE TITLE
Allow supporting more languages

### ISSUE THREAD

**Issue by pktiuk** [mrinc/Facebook-Hide-Recommendations-and-Reels#18]
It would be good to have support for more languages, or at least create a simple guide for contributors how to add new language and create PR.
(You could also use [weblate](https://weblate.org/en/) for this purpose)

**Comment by AnKO314** [comment]
If you look at the Pull Request concerning French, the commit looks like this : 

`  fr: {
    newsFeedPosts: "Messages du fil d'actualité",
    reelsBlock: "Reels et courtes vidéos",
    commentedOn: " a commenté un message de ",
    peopleKnow: "Les gens que vous connaissez peut-être",
    suggested: ">Suggéré pour vous<",
  },`

So I guess you can translate this piece of code for the language you want and maybe it will be added

**Comment by mrinc** [comment]
@pktiuk @AnKO314 

On my task list next week to get back to this project with a cleanup and update :) 

However in the interim, you can add more langs but just adding more items to the array - https://github.com/mrinc/Facebook-Hide-Recommendations-and-Reels/blob/master/src/content.js#L1 

We just match the lang in the browser, so 2 char lang code.

Use EN as the basis, and copy the text from your FB app - so it matches exactly to what they have.  

Push through a PR and I'll look at it when I am back on this :) 

As for automatic text - it's more important to match exactly what FB says rather than what might be correct.

**Comment by mrinc** [comment]
```
en: {  
    newsFeedPosts: "News Feed posts",  
    reelsBlock: "Reels and short videos",  
    commentedOn: " commented on a post from ",  
    peopleKnow: "People you may know",  
    suggested: ">Suggested for you<",  
  },  
```  

Just a few items to match and we can add a new lang :)

**Comment by pktiuk** [comment]
This process seems to be really simple. I think you should just put these information in README, and it would be fine and may encourage people to add new langs :)
