### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by karigithub2000** [mrinc/Facebook-Hide-Recommendations-and-Reels#36]
This plug in worked fantastically to block Facebook suggested content, but ceased working today. Sometimes when this happens it will work again if I refresh the page, but this has also not solved the issue. Over half of my feed is currently reels and suggested content.

**Comment by mrinc** [comment]
Hey,

Please advise browser, version of FBHRAR and language?

Thanks

**Comment by mrinc** [comment]
@karigithub2000 I am just going to close this issue so long, please re-open it when you get a chance to reply :) 

** If you are using firefox, I can understand the issues experienced .... we're working on trying to get the latest release on firefox ... their process is great for safety, but a bit of a pain since we now compile ts to js.  So we are quite a few versions behind for firefox users.  (which include a debugging tool from v1.26)  
Once they are happy with our release process, it should go up and you'll get the latest fixes :)
